server:
  port: 0

spring:
  application:
    name: movie-rating-data-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
